### ISSUE TITLE
Investigate improving API

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1004]
[Goals and potential approaches document](https://docs.google.com/document/d/1-u5lYT24XZwP0MRQu0NE2B9coZWVAfnk8f0F1GXuDRo/edit?ts=6018736f#)

Refs #1007

**Comment by chigby** [comment]
Some insights gained via some profiling I've done with [django-silk](https://github.com/jazzband/django-silk).  Most of the slownesses I found were related to database queries being executed.

1. The `export` view is not very well optimized to minimize DB queries, particularly the JSON-formatted view. This probably should be fixed no matter what implementation route we want to take. But it is also slow because we are returning many incidents at once.
2. Retrieving image renditions, e.g. for teaser images, requires querying the database.
3. Rendering `StreamFields` is somewhat performance intensive. The process can include making DB queries for things like images, which is something I didn't realize before.
4. Getting the URL of a page from wagtail involves querying the database at least once. 
5. The topic page API view is fairly well optimized but still involves rendering streamfields and finding URLs. We are helped by the fact that the number of incidents returns is limited.

I'm inclined to see what we can gain by trying to pre-generate (as described in the approaches document) the export view. This technique is less disruptive to our codebase than bringing on board something like Django Rest Framework, and I think we could accomplish a lot of our stated goals with a little thought to how we want to design some different, yet limited, datasets to pre-generate. 

The topic page view I'm less certain about, and we should discuss more.

**Comment by chigby** [comment]
Having deployed one batch of performance improvements to the current export API, here's my current thinking on where we ought to look next.

Given that:

- In production, we are using the export API (with filters and a subset of fields) to power the data viz. We're achieving acceptable performance via Cloudflare caching.
- The topic page API and the export API use almost completely distinct code.
- The topic page API might be better thought of as the Categories API, since it primarily delivers information about our incident categories.
- The export API primarily delivers information about Incidents themselves.
- There is a limit to our ability to optimize exporting all incident information, particularly the article text fields. These are always going to be somewhat slow and that slowness will be linearly proportional to the number of incidents being exported.

I think it might be premature to write a bunch of code to manage pre-generated (i.e. cached) API results. I had been thinking "export" was a different enough use case from "granular API" that those two features could be separated within our site's code. But we still need, broadly, a way for our front end components to get Category and Incident data. Even if we were to pre-generate export results (with a few preset filters), I do not believe they would optimally serve the purpose of developing novel ways to display the data on the website. We need a granular API anyway, and we want it to be good, and if it's good, it ought to be able to serve as an export API -- and if it doesn't, or that turns out to be harder than we thought, we can revisit the question of how to make exporting separately behave how we want it to.

So my opinion is now that our efforts ought to go towards building a unified Incident and Category API. I'm rethinking what I said above about Django Rest Framework: since wagtail depends on it, and thus it's already installed for us. And currently our API code is very ad-hoc and not standardized. Unifying it all into one set of views, urls, and one framework would be a big improvement to our ability to work with the API code in general (i.e. extending it, improving its performance, etc). If we build this parallel to what we already have, we can fairly directly compare the performance of each. 

On the subject of other goals: Django rest framework seems fairly capable of supplying the versioning, aggregation, and consistency features we like. Though I did also notice [the Django Ninja](https://django-ninja.rest-framework.com) project. As far as our goal of "flexibility" I did find this somewhat intriguing: [DRF flex fields](https://github.com/rsinger86/drf-flex-fields). And potentially this [auto prefetcher](https://pypi.org/project/django-auto-prefetching/) -- but both of these require a little more research.

**Comment by harrislapiroff** [comment]
Given the constraints you've outlined and the performance improvements you've already been able to make to our existing API, I think moving forward with a more fully featured REST API seems like a reasonable approach!

I'll also observe that this approach does not necessarily preclude us in the future from selecting certain common queries to pregenerate and cache in the future if we need further performance boosts—and even adding special endpoints for those if we want.

One request I would make is that, while building out a REST API, you attempt to leave CSV formatting as an option, since queries for the entire database can be pretty large and they'll be quite a bit smaller as CSV than JSON. (If this is too big of a challenge, I'm open to forgoing it.)

**Comment by chigby** [comment]
Given our discussion in web meeting today, here's a slightly more detailed write-up of what I'm proposing (and have begun preliminary work on)

1. A single JSON API framework that provides what we need to support the features and capabilities of our three main JSON views:
    - The incident export view
    - The topic page incident categorization view
    - The [incident target summary view](https://github.com/freedomofpress/pressfreedomtracker.us/blob/43bba211d866d866b73f48ead6c66dc2bd9f2435/incident/models/incident_index_page.py#L138-L144) (used by the admin statistics editing widget).
2. Move all URLs into a single `/api/v1/` (or similar) prefix. 
3. The incident export view 
    - Becomes the `/incident/` endpoint. Right now, the export API is prefixed by the particular `IncidentIndexPage` that contains the incidents you want to export.
    - Should be able to list all incidents, or retrieve a specific one with `/incident/<primary key>/` (right now, only listing is possible).
    - Retain the ability to get CSV-formatted data with [django-rest-framework-csv](https://github.com/mjumbewu/django-rest-framework-csv).
    - Replace comma-separated string fields (e.g. charges, venues, nationalities) with proper JSON list fields. The former were being used for CSV compatibility, which I think is handled for us by django rest framework.
    - **Open question**: Most of the models related to `Incident` have a single `title` field, and thus representing them as JSON lists of strings is fine. However, some fields contain more data fields (e.g. targeted journalists, equipment damaged/seized, links) and can now be represented as JSON objects directly, rather than as formatted strings (such as equipment rendering as "iPhone: count of 3"). We could keep them as strings, though, if we wanted. An even fancier approach would be to use something like DRF flex fields (mentioned in the comment above), for Stripe-style "expanding fields" functionality (though, I will note that the linked library is not quite at a 1.0 version).
    - The `subpoena_statuses` field is an Array field. In the current system, it is exported as the _string representation of an array_, (`"['item one', 'item two']"`) which IMO is a bug. See [a sample API query](https://staging.pressfreedomtracker.us/all-incidents/export/?categories=6&format=json) for a demonstration.
    - The authors field does not currently show the author name. See [this example](https://staging.pressfreedomtracker.us/all-incidents/export/?format=json&categories=5&date_lower=2017-05-14&date_upper=2017-05-20). It should be fixed to show that information at the very least.
    - Keep existing filtering-by-querystring behavior.
4. Topic page API / Category API
    - Becomes the `/category/` endpoint
    - Contains nested Incident data (using the same format as the incident API above)
    - Retains the aggregation features (counting total journalists, total incidents)
    - **Open question** Possibly moves `incidents_per_module` (currently a data field on the topic page model) into some kind of nested-pagination parameter. Need more research on if this is possible and/or a good idea in DRF. If not, it can probably stay as it is.
5. Summary API -- my inclination here is to move this to its own `/summary/` endpoint and leave the functionality the same. Though there is an argument for not even touching this at all and letting it continue to be a single-purpose helper for the Statistics widget and not opening it to the public. There might be potential for future work in building out a more feature-full aggregation/summary/statistics API, though. I haven't thought about this one that much because until this week I had kind of forgotten about it.

**Comment by harrislapiroff** [comment]
A few items for improvement

- [x] Implement [pagination](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1019#issuecomment-818001970)
- [x] [Temporarily move endpoint](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1019#discussion_r611726700) from `api/v2` to `api/edge` or `api/beta`
- [x] Add an API root that lists endpoints

**Comment by harrislapiroff** [comment]
A couple more items

- [x] Change `slug` to `url` and include the full URL to the HTML version of the incident
- [x] Put CSV columns in the same order as the JSON keys

**Comment by eloquence** [comment]
All improvements noted above were completed and the first version of this API is live; further improvements will be tracked as separate tickets.
