### ISSUE TITLE
Update Analytics tracking code

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1010]
Looks like the current Matomo tracking code looks like this. It's not so different from what we have now, but it might be worth updating just in case:

```html
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://analytics.freedom.press/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '5']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

N.b., adding this code will also involve removing the script tag in the template loading `https://analytics.freedom.press/piwik.js`

**Comment by chigby** [comment]
I'm not sure we're able to use the standard Matomo tracking code as an inline script without making our CSP more complicated (there's some discussion of this in https://github.com/freedomofpress/securedrop.org/pull/771). Our current Matomo tracking setup, with the separate script tags in our base template, was taken from [this page in the Matomo help section](https://matomo.org/faq/general/faq_20904/) and doesn't seem like it's changed? If the code is causing problems we can definitely investigate, though.

**Comment by harrislapiroff** [comment]
I didn't mean to use it as an inline script, I meant that we should update our matomo script file to match the recommended script. (Which does differ in some small, but non-functionality altering ways, I believe.)

**Comment by chigby** [comment]
Gotcha, I can do that. Though I think the script in the issue description is not completely accurate, as it looks like we are using `piwik.php` instead of `matomo.php`.
