### ISSUE TITLE
Arrests category improvements

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1018]
The current structure of charges in the database needs some finessing. In particular, we want to be able to associate charge status with specific charges since a journalist may be charged with multiple things and one may be dropped and the other not. We also want to record a timeline of when charges get dropped, go to trial, undergo appeal, etc.

Let's add the following to incidents:

An inline `IncidentCharge` object with a nested inline `ChargeUpdate` object.

Charge should have a single autocomplete field to charges

ChargeUpdate should have: date and status. It's possible we'll add other fields (such as date of trial) but I need a little time to think about how they should be structured.

We'll also need a migration to move data from the old fields in a logicial way, but we should probably preserve the old fields deprecated for at least a month.

**Comment by KAMcCudden** [comment]
Sent via slack to HL on March 19 but also uploading here for review:
[Outline of recommendations for improved back-end functionality following ‘acute’ increased usage](
https://docs.google.com/document/d/1vNaKJLXgWnm7i4YgZvQgUyC-sMQgpsAghEZys8BxGss/edit#heading=h.p7fs7uavw6qk)

**Comment by eloquence** [comment]
(Next step is for @harrislapiroff to review above and flesh out this ticket, or kick it over to Saptak/Cameron.)

**Comment by harrislapiroff** [comment]
This is now fleshed out and ready for development

**Comment by chigby** [comment]
Potential snag: nested inline panels are bugged. See https://github.com/wagtail/wagtail/issues/5770

**Comment by harrislapiroff** [comment]
Is this fixed in the latest wagtail? Maybe we should prioritize upgrading PFT? Alternatively can we patch this fix in by overriding the specific javascript staticfile temporarily?

**Comment by chigby** [comment]
According to the wagtail 2.15 changelog, it is fixed.

**Comment by harrislapiroff** [comment]
Let's put this on our list for January. It's not a redesign task, but the tracker team would really like to have it. (And we have to update Wagtail in January regardless.)

**Comment by stephaniesugars** [comment]
Per our conversation during web sync on Monday, adding to the cue for the arrest metadata:

- renaming the back-end description to match the category name ("arrest/criminal charge")
- adding "charged without arrest" as an arrest status
- move the arresting authority entry to the top
