### ISSUE TITLE
Add content security policies

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1024]
Like the other repos, we would need to add CSP rules using django-csp for this repo as well.

**Comment by prateekj117** [comment]
@SaptakS I can have a look into this.

**Comment by SaptakS** [comment]
Sure! Go ahead! You can check the CSP [implementation using django-csp for securedrop](https://github.com/freedomofpress/securedrop.org/blob/develop/securedrop/settings/base.py#L318-L371). It should be similar. There will be few additional rules needed in tracker though.

**Comment by prateekj117** [comment]
Sure. Sounds good. Will have a look at CSP rules in `SecureDrop` and `securethenews`. And will ask here if any doubts.
