### ISSUE TITLE
Document the current `edge` API

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1042]
Let's write some documentation for the new `edge` API, with the understanding that it's still changing and will eventually be released with a version number.

Feel free to write the documentation in a text editor of your choice and @harrislapiroff will convert it to the web.

**Comment by eloquence** [comment]
We do have live docs on https://pressfreedomtracker.us/data/ which we'll aim to keep updated for now; we may revisit our strategy for updating docs/automating docs generation in future.
