### ISSUE TITLE
RSS feed is massive and unpaginated

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/pressfreedomtracker.us#1058]
https://pressfreedomtracker.us/all-incidents/feed/ regularly clocks in as a slow page request at >20 seconds, and that should not be surprising -- it's a 5.3M file that appears to include all incidents going back to January 2018.

It's standard practice to truncate feeds after a limited number of items (e.g., 15). We could use `<link rel="next">` to paginate the feed.

**Comment by prateekj117** [comment]
@eloquence @SaptakS Can I take this up?
