### ISSUE TITLE
[API] Add longitude and latitude fields to tracker 

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1062]
This would be useful for anyone trying to make map-based visualizations.

These fields can be purely derived from city/state. We should specify in the docs at the same time that they represent approximate, not precise, locations.

Not sure what geocoding backend makes sense to use, so research required there. If we need to rely on raw data, I've created a CSV of cities with lat/long/pop here: https://observablehq.com/d/808d887451a25d6a

**Comment by harrislapiroff** [comment]
(Currently I'm loading that CSV on the frontend to do some brute force geocoding for the map viz 😅, but doing it that way has limitations)

**Comment by chigby** [comment]
Potentially useful: https://geocoder.readthedocs.io/
