### ISSUE TITLE
Incident API: Limit number of results by default

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1065]
Right now, a request to the root of the incident API returns every incident in the database. We would like it to paginate that list by default for the JSON view, with a reasonable limit in place. I'd suggest 25. The CSV view should continue to not paginate.

See aa4950d6fe689d9c4b707ae2e25fd141e9c2774d

**Comment by prateekj117** [comment]
@chigby @SaptakS Can I take this up?

**Comment by chigby** [comment]
@prateekj117 Yes, definitely. Feel free!
