### ISSUE TITLE
TIPS submission portal on web not working

### ISSUE THREAD

**Issue by KAMcCudden** [freedomofpress/pressfreedomtracker.us#1088]
We've received two reports and I tested as well -- the tips form <<Submit an Incident>> on PFT is giving an error and is unusable right now. Even when all the fields are filled out, the form says "This field is required" and a tip cannot be submitted.

URL: https://pressfreedomtracker.us/submit-incident/

![Screen Shot 2021-06-16 at 07 03 34](https://user-images.githubusercontent.com/46460749/122224230-86a11380-ce79-11eb-9b0f-a77b1f2055fc.png)

**Comment by harrislapiroff** [comment]
Resolved in #1089
