### ISSUE TITLE
[API] Add pagination headers

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1093]
Let's use the `Link:` response header to add pagination info (see an example in [GitHub's API docs](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#pagination). This is a semi-standardized best practice, I believe, and it will enable pagination on CSV, where we are unable to provide an "envelope" in the content of the response.

Note:
* We can also add links for `"first"` and `"last"` in addition to `"next"` and `"previous"`
* We could consider adding custom data to headers, e.g., `X-Total-Count`
* We should make a decision as to whether to leave the envelope with pagination info in the JSON response as a redundant measure (particularly for developers who are not experienced with or don't have access to HTTP headers) or remove it for consistency

**Comment by chigby** [comment]
I don't think we can add the `"last"` link because we're using cursor pagination, which if I understand correctly, does not permit jumping to an arbitrary page index.

**Comment by harrislapiroff** [comment]
Ohhh that makes sense.
