### ISSUE TITLE
Check in Kibana for PFT cache invalidation messages, to determine if we're ready to increase cache time >5 minutes

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1116]
Blocked on #1115

**Comment by harrislapiroff** [comment]
No longer blocked. Someone should take a look at prod logs in kibana and see if logs are showing up for all the cache trigger signals we have.

**Comment by chigby** [comment]
Page purge logs (within the past 2 hours) on:

1. [Staging](https://logs.freedom.press/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(django.event),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.container_name,negate:!f,params:(query:pressfreedomtracker),type:phrase),query:(match_phrase:(resource.labels.container_name:pressfreedomtracker))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.cluster_name,negate:!f,params:(query:www-staging),type:phrase),query:(match_phrase:(resource.labels.cluster_name:www-staging)))),index:'filebeat-*',interval:auto,query:(language:kuery,query:'django.event:%22Purged%20page%22'),sort:!()))
2. [Production](https://logs.freedom.press/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(django.event),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.container_name,negate:!f,params:(query:pressfreedomtracker),type:phrase),query:(match_phrase:(resource.labels.container_name:pressfreedomtracker))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.cluster_name,negate:!f,params:(query:www-production),type:phrase),query:(match_phrase:(resource.labels.cluster_name:www-production)))),index:'filebeat-*',interval:auto,query:(language:kuery,query:'django.event:%22Purged%20page%22'),sort:!()))

Also: [staging logs showing me performing some updates and deletions](https://logs.freedom.press/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-30T14:30:00.000Z',to:'2021-08-30T16:00:00.000Z'))&_a=(columns:!(django.event),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.container_name,negate:!f,params:(query:pressfreedomtracker),type:phrase),query:(match_phrase:(resource.labels.container_name:pressfreedomtracker))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.cluster_name,negate:!f,params:(query:www-staging),type:phrase),query:(match_phrase:(resource.labels.cluster_name:www-staging)))),index:'filebeat-*',interval:auto,query:(language:kuery,query:'django.event:%22Purged%20page%22'),sort:!()))

Also also: [production logs of pages purged in August 2021](https://logs.freedom.press/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-01T14:29:23.469Z',to:'2021-08-30T16:00:00.000Z'))&_a=(columns:!(django.event),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.container_name,negate:!f,params:(query:pressfreedomtracker),type:phrase),query:(match_phrase:(resource.labels.container_name:pressfreedomtracker))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.cluster_name,negate:!f,params:(query:www-production),type:phrase),query:(match_phrase:(resource.labels.cluster_name:www-production)))),index:'filebeat-*',interval:auto,query:(language:kuery,query:'django.event:%22Purged%20page%22'),sort:!()))

**Comment by chigby** [comment]
The purges are happening in production, I'm considering this issue resolved.
