### ISSUE TITLE
[API] Update consumer documentation

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1117]
[The documentation](https://pressfreedomtracker.us/data/) needs to be update to reflect recent changes including

* Default pagination limit

**Comment by chigby** [comment]
I think the default pagination limit docs were updated in https://github.com/freedomofpress/pressfreedomtracker.us/commit/6b54699b6ff309189761bbf1447444a7df4d077c -- part of #1151. Are there other things that we ought to have for this issue?

**Comment by harrislapiroff** [comment]
I think we can probably close this in that case!
