### ISSUE TITLE
New feature: Increased options in metadata in Subpoena category

### ISSUE THREAD

**Issue by KAMcCudden** [freedomofpress/pressfreedomtracker.us#1125]
The Subpoena/Legal Order category covers technically distinct _subpoena_ and _legal order_ press freedom issues. 
Two issues to review:
1. The drop-down menu for subpoena says "Subpoena of Journalism (incl. Legal Case)" 
It can simply say "Subpoena (incl. Legal Case)"  

2. (More important issue) In the drop-down menu for subpoenas, there are a handful of options, including "Subpoena Statuses" as shown on the attached screenshot. 

Directly below the Subpoena drop-down is the Legal Order drop-down, named "Legal Order for Journalist's Records (incl. Legal Case)." Can we please add the same option of checkboxes to this menu.

In that menu, there are three fields to fill out. The new "Legal Order Statuses" should directly follow "Legal Order Type," mirroring the subpoena options.
Let me know if there are any questions.  

<img width="1007" alt="Screen Shot 2021-08-31 at 2 37 09 PM" src="https://user-images.githubusercontent.com/46460749/131875635-2355097f-a3df-4a20-aeeb-b468f9b69c98.png">

**Comment by harrislapiroff** [comment]
When Kirstin refers to drop-down here, she's talking about the `MultiFieldPanel`s and their titles.

For the second item, just duplicate the "Subpoena statuses" field into a "Legal statuses" field.

**Comment by harrislapiroff** [comment]
I think this PR is superceded by the work on #1582
