### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1132]
We'd like to upgrade from React 16.13.1 to version 17.x. Here's a [post describing what's new](https://reactjs.org/blog/2020/10/20/react-v17.html).

I think there is an issue preventing the upgrade right now, which is the lack of an official Enzyme adapter for React 17. There is an in-progress issue in that repository (https://github.com/enzymejs/enzyme/issues/2429) that we can monitor for when it's ready.

**Comment by harrislapiroff** [comment]
This appears to still not be resolved almost a year later. I think it may be time to discuss an Enzyme exit strategy.

**Comment by harrislapiroff** [comment]
Also updating this and the other ticket to reflect upgrading to React *18* now

**Comment by harrislapiroff** [comment]
Looks like there's an unofficial adapter here if we'd rather keep using it https://www.npmjs.com/package/@zarconontol/enzyme-adapter-react-18

**Comment by harrislapiroff** [comment]
As discussed during our quarterly dependency review, we will be pursuing `react-testing-library` as a replacement for enzyme. Our enzyme tests are largely outdated and can be abandoned. This is now unblocked.

**Comment by chigby** [comment]
So, one possible problem here is [`react-animated-dataset`](https://github.com/accurat/react-animated-dataset) supports only up to react 16:

https://github.com/accurat/react-animated-dataset/blob/85ffee3dd6d78060f73b43d1557b91cd11a50530/package.json#L39-L40

**Comment by harrislapiroff** [comment]
@chigby will attempt solving https://github.com/accurat/react-animated-dataset/issues/17 on his own and putting in a PR to Accurat. If it turns out to be more complicated than just bumping/opening version reqs, he'll pause and bring it back for discussion (and alert Accurat)
