### ISSUE TITLE
Wagtail autocomplete makes multiple requests for deleted items

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1138]
We were seeing a spike in `/autocomplete/objects/` path when opening an all-incidents page with an autocomplete filter for an item that was deleted. When autocomplete sees that the request returned with empty items list, the autocomplete attempts to fetch info again and again, hence creating huge number of requests to `/autocomplete/objects/`

The two things we need to decide is:
- Find if we can send a better error response in case the item being filtered by is deleted.
- If we can't provide a better response, restrict the requests to `n` failures, after which it shouldn't send any more requests.

**Comment by SaptakS** [comment]
We will need to make a PR here once a new wagtail-autocomplete release has been made with the delete item fixes

**Comment by harrislapiroff** [comment]
Looks like this is still waiting on a wagtail-autocomplete release. I believe @chigby has the ability to issue those. @SaptakS if you give me a PyPI username I can add you as well

**Comment by chigby** [comment]
This can be done once https://github.com/wagtail/wagtail-autocomplete/pull/104 is merged

**Comment by SaptakS** [comment]
@chigby Done!

**Comment by SaptakS** [comment]
I think we can close this since this is just waiting on deploy?

**Comment by SaptakS** [comment]
Closing this since the fix has been deployed in all sites.
