### ISSUE TITLE
Make cases statuses searchable

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1163]
Currently case status is linked in the sidebar of incidents, but it doesn't lead to a properly filtered page when you click on it:

![image](https://user-images.githubusercontent.com/296631/145268226-7cb573cd-411b-46ef-9994-5cd1d4d2c5c9.png)
[Example](https://pressfreedomtracker.us/all-incidents/journalist-graduate-student-stopped-secondary-screening-electronic-devices-searched/)

Normally to enable this functionality we'd add "Case statuses" as a "General incident filter" in Wagtail's admin under Settings > General incident filters, but it doesn't seem to be an option in the dropdowns there. (The other field @SaptakS added—"Case number"—is there. Not sure what needs to be done to register this field.)

**Comment by SaptakS** [comment]
@harrislapiroff it's verbose name is "Legal case status", so it appears as "Legal case status". Can you test with that once? Also do you want the verbose name to just be "Case status" ?

**Comment by harrislapiroff** [comment]
@SaptakS Ok, search works, thanks! But the link still generates a non-filtered URL. So probably there's a template level fix
