### ISSUE TITLE
Redesign: Incident Card, Part 1

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1173]
- [ ] Big
- [ ] Big w/ photo
- [ ] Small
- [ ] Small w/ photo

[Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=2710%3A22015)

When closing this ticket, open a ticket **Redesign: Database Card** and the same figma link

**Comment by chigby** [comment]
Question about these cards: there are 4 designs here, but they differ in very small ways. Do we want to create four separate HTML files that can be separately invoked via an `include` statement (for example `{% include "incident_card_big_photo.html" %}`)? From looking at these, the difference between the big and small cards is the width, which I would have assumed would be non-fixed and based on the properties of the element containing the card (or something like a media query). The difference between the photo and non-photo cards is whether to use display a photo or a teaser text. But these are both optional fields on the `Incident` model, and (again) I would have assumed that the card template would have internal conditional logic for prioritizing the display of these fields. So maybe I have some misunderstandings of the main ideas here, or possibly just need some clarification of exactly what is needed for this issue to be resolved.

**Comment by SaptakS** [comment]
I would think of passing some arguments that make distinction maybe? Like if `{% include "incident_card.html" with photo=incident.image and size="big" %}` is called, then we can check in the template these two parameters and decide the small changes? Or basically just add this arguments to the the class names somehow that we can different it in the sass file? What do you think @harrislapiroff ?

**Comment by harrislapiroff** [comment]
After discussing in web sync, we've decided to use a single template with context variables for whether to display a photo and whether to display large or small (which only changes the heading size) as @SaptakS proposed
