### ISSUE TITLE
Upgrade to Wagtail 2.15.x LTS

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1188]
Not technically a redesign task, so please base an upgrade branch off of `develop` when putting in a PR and we'll merge it to `develop` first and then rebase `redesign` off of `develop` (or merge—TBD).

**Comment by kevinhowbrook** [comment]
WIP for this is here https://github.com/freedomofpress/pressfreedomtracker.us/pull/1190

At the moment I'm combing through failing tests :)

**Comment by kevinhowbrook** [comment]
As this stands the tests are passing but the CI is failing on CVE alerts for Pillow https://app.circleci.com/pipelines/github/freedomofpress/pressfreedomtracker.us/1813/workflows/d89ddf1d-66fd-4b5c-a4b2-84a49d22d6bb/jobs/10207?invite=true#step-103-55

**Comment by SaptakS** [comment]
I am updating pillow everywhere. So after that's merged and you rebase, that alert should go away.
