### ISSUE TITLE
Categories block

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1193]
Create categories block as outlined in the Figma design.

Desktop:
![image](https://user-images.githubusercontent.com/561931/149016608-e62dd5ac-5ff1-4b55-adfe-188c4466388c.png)

Mobile:
![image](https://user-images.githubusercontent.com/561931/149016958-0f4ea60c-491c-4203-9139-a941f64f6d94.png)

Tablet:
![image](https://user-images.githubusercontent.com/561931/149017012-72cbb64c-74c2-476c-90e2-10b9d41be11d.png)

**Comment by chigby** [comment]
Question for @harrislapiroff and @SaptakS and anyone else: is the above layout actually possible using CSS only? I am having a hard time getting the borders on the category items to "collapse" as shown -- meaning arranging it so that the borders between the items is the same as the border around the outside. Everything I've tried ends up with "doubled" internal borders or changing the design somehow, such as forcing each row to take up the same width, as shown:

![image](https://user-images.githubusercontent.com/561931/149019641-5c21f976-d117-4022-ab2b-607c3345a91d.png)

Any thoughts on this one? My CSS may not be up to the task here.

**Comment by SaptakS** [comment]
This should be possible to do. Let me look into it a bit more and might have a better solution.
