### ISSUE TITLE
Blog stream blocks

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1199]
This should be completed after #1186 

Refer to the [Newsletter/Article/Special Section artboards](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3698%3A62440) to generate a list of necessary blocks. Wherever possible, reuse the same Python/HTML/CSS as for incident detail blocks from #1186.

**Comment by urlsangel** [comment]
Hi @harrislapiroff 

I've reviewed the Article/Blog page type in Figma, and these are the blocks that I think are required in the body content:

#### Existing blocks
- AlignedCaptionedImageBlock (as used on incident page)
- PullQuoteBlock (as used on incident page)

#### New block
- ResourcesBlock (new block, list of resource links and sources, with optional title)

<img width="592" alt="Screenshot 2022-01-28 at 14 19 57" src="https://user-images.githubusercontent.com/560463/151562956-06ad644e-c345-4ebe-b0c6-d66981e50485.png">

#### Model field
There's an "Editor's note" module at the base of the article - this doesn't feel like a content block, but more suited to being a field on the model?

<img width="619" alt="Screenshot 2022-01-28 at 14 22 00" src="https://user-images.githubusercontent.com/560463/151563083-28c459aa-417d-4964-9e81-63f57f2228ec.png">

**Comment by harrislapiroff** [comment]
Instead of calling that a `ResourcesBlock` let's call it an `AsideBlock` that's basically just a rich text block and let editors use it for both those type of resource lists and those editor notes. I'm seeing that in practice content editors have been using teal text blocks for this sort of thing [on the live site](https://pressfreedomtracker.us/blog/at-least-60-journalists-have-sued-police-following-arrests-assaults-at-protests/).

**Comment by urlsangel** [comment]
> Instead of calling that a ResourcesBlock let's call it an AsideBlock that's basically just a rich text block and let editors use it for both those type of resource lists and those editor notes. I'm seeing that in practice content editors have been using teal text blocks for this sort of thing on the live site.

@harrislapiroff - Cool, in essence it's just a rich text block but reversed right?

**Comment by harrislapiroff** [comment]
Yep! Exactly

**Comment by urlsangel** [comment]
Hi @harrislapiroff 

The blog page model body streamfield includes the `StyledTextBlock` from here:

https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/common/blocks.py#L125

This has a `background_color` choice field which uses `BACKGROUND_COLOR_CHOICES` from here:

https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/common/choices.py#L18

I can't see any references elsewhere in the code base these color names such as `gamboge` or `eastern-blue`, and these aren't valid HTML color names, so I'm not really sure what we're supposed to with them in terms of inline styling?

The `StyledTextBlock` also has `font_size` choices which I'm not sure what to do with either:

https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/common/blocks.py#L132

Any clues on what to do with these?

**Comment by harrislapiroff** [comment]
For now, let's add a comment to those fields saying they're deprecated and ignore them. We won't be using them. At some point we'll need to check what they're being used for in practice on production and write migrations for them. I suspect we'll be converting a lot of the blocks with a specified background color to asides

**Comment by chigby** [comment]
Closed by #1223
