### ISSUE TITLE
Database page: Integration, basic

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1220]
Depends on #1219

Make form filters functional. Pure HTTP/GET requests with full page reload for this iteration. No javascript.

**Comment by urlsangel** [comment]
@harrislapiroff @chigby 

I think this issue is will be resolved naturally by the implementation of Django forms as per https://github.com/freedomofpress/pressfreedomtracker.us/issues/1218

**Comment by harrislapiroff** [comment]
This is done
