### ISSUE TITLE
Focus state on links should not cause reflow

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1265]

**Comment by chigby** [comment]
I have been poking at this a little bit, and I noticed that for the focus styles on buttons and some other elements, we are specifically removing the `outline` styles and manipulating the border, which is what is causing the changes in the element spacing on focus. Maybe this is something that was already discussed, but I am curious: Is there are reason we are not changing (rather than disabling) the outline style for focused elements? I was not super familiar with this property, but the [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/outline#description) says:

> Unlike other areas of the box, outlines don't take up space, so they don't affect the layout of the document in any way.

And it seems to me like if what we want for focus styles is drawing a black border around borderless objects, or thickening the border around bordered objects, without causing the document to shift, then can we achieve that with setting, for example, `outline: black solid 3px`? And since the layout would be unaffected, we could avoid negative margins and transparent borders.

@SaptakS @harrislapiroff Let me know if you have thoughts on this or if I'm overlooking something here.

**Comment by harrislapiroff** [comment]
@chigby Outline is OK with me. I forget if there was a reason we opted out of that approach, @SaptakS ?
