### ISSUE TITLE
Redesign: 500 on incident categories in "Learn more about our Categories" section

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/pressfreedomtracker.us#1275]
Dear PFT team,

First of all - the redesign looks great, congratulations!
 
I just noticed that clicking on the incident category labels in "Learn more about our Categories" (corresponding to `/arrest-criminal-charge/`, `/border-stop/`, `/chilling-statement/` etc) results in 500 errors- sorry if this is a duplicate/known issue, but didn't see it in a quick search.

**Comment by SaptakS** [comment]
This will be fixed once https://github.com/freedomofpress/pressfreedomtracker.us/pull/1271 gets merged

**Comment by SaptakS** [comment]
@rocodes This should not be throwing 500 anymore and should be okay to be closed. Let me know if you still face this issue.
