### ISSUE TITLE
Home page charts CSS errors

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1293]
When hovering the mouse cursor over the category boxes on the home page chart controls, in Firefox, I'm noticing a large number of errors in the console (visible if CSS warnings are turned on):

![image](https://user-images.githubusercontent.com/561931/160000939-69af2857-1a28-42b6-8858-d050ba6d48df.png)

**Comment by chigby** [comment]
The "Error in parsing value for `left`" and "Error for parsing value for `top`" are being caused by this:

https://github.com/freedomofpress/pressfreedomtracker.us/blob/1a635034f78152a63c1ecfd3911073ec44736ca3/client/charts/js/components/TreeMap.jsx#L122-L124

When the `AnimatedDataset` component calls it, it is not passing `MouseEvent`, as an argument, it's passing `datum, index, nodes`, which is behavior in line with an older version of d3-selection, specifically [version 1.4.1](https://github.com/d3/d3-selection/tree/v1.4.1#handling-events). I'm not sure how to work around this.

The "Error in parsing value for `fill`" is, I think, being caused by this line:

https://github.com/freedomofpress/pressfreedomtracker.us/blob/1a635034f78152a63c1ecfd3911073ec44736ca3/client/charts/js/components/TreeMap.jsx#L288

It's hard for me to figure out the intended behavior for this one. If I change the callback function to a hard-coded value (e.g. "#CCCCCC"), the error goes away but I also don't see what changes in the chart.

**Comment by harrislapiroff** [comment]
Thanks for tracking it down. I’ll take a look. I bet I can suss out intended behavior.

**Comment by harrislapiroff** [comment]
Actually looking at it now I wonder if the second one is just a copy paste error. Lines don’t usually have a fill.
