### ISSUE TITLE
How are categories ordered on the home page charts?

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1315]
Should probably either be by size or alphabetically. Currently appears random.

**Comment by chigby** [comment]
It is determined by the order of the entries in this object:

https://github.com/freedomofpress/pressfreedomtracker.us/blob/8cf28948876ae51924f74cd1dc0035c153358c40/client/charts/js/lib/utilities.js#L186-L198

**Comment by chigby** [comment]
Resolved by #1340
