### ISSUE TITLE
Submitting incident gives 500 error

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1330]
We should figure out why to ensure we're not launching a regression

**Comment by SaptakS** [comment]
The captcha issue has been solved by https://github.com/freedomofpress/k8s-configs/pull/257 but on submitting an incident, its giving a 500.

**Comment by SaptakS** [comment]
This page is working fine. In redesign, it's failing because of mailgun settings but that is expected. Closing this.
