### ISSUE TITLE
Update categories API; Update javascript to use API

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1338]
Currently category data is hardcoded into a couple places in the charts javascript. We should generate this on the server side and feed it the javascript. We could do this in a django template or via API after #1337 

https://github.com/freedomofpress/pressfreedomtracker.us/blob/redesign/client/charts/js/components/HomepageMainCharts.jsx#L18

https://github.com/freedomofpress/pressfreedomtracker.us/blob/redesign/client/charts/js/lib/utilities.js#L186

**Comment by harrislapiroff** [comment]
We now have an endpoint with a list of categories: https://pressfreedomtracker.us/api/edge/categories/

It's possible we need to add slugs to that endpoint

**Comment by shanejdonnelly** [comment]
@chigby @harrislapiroff The endpoint above is really close to slugs === 'page_symbol', but not quite. (I don't know what the 'page_symbol' is for...)

- So I guess we need to add the slugs to the endpoint? We don't want to change slugs to match the page_symbol, right?
- Do we want to add the categoriesColors to the endpoint as well?
- Should we have an 'order' field so the order can be changed to something other than alphabetical?

**Comment by harrislapiroff** [comment]
I think `page_symbol` is supposed to be the class name used for rendering the SVGs that represent category symbols. @chigby can you assist with cleaning up this endpoint as part of this ticket? I'm thinking:

- [ ] Rename `page_symbol` to something more meaningful
- [ ] Add a `symbol_url` that provides a path to the SVG, maybe
- [x] Add a `slug` that provides the page slug
- [x] Add a `url` that provides the category page full url (I know it's kinda redundant with slug, but it seems nice)
- [ ] Run the `methodology` field through Wagtail's rich text processor

Re: category colors: One thing emphasized to us by Accurat with this new design was *not* to create a strong association between colors and categories, so let's just keep the colors hard coded in the javascript and assign them to categories in alphabetical order.

Let's just keep order alphabetical.
