### ISSUE TITLE
Aside background should hug text

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1377]
As seen in figma:

![Screen Shot 2022-04-05 at 3 49 22 PM](https://user-images.githubusercontent.com/296631/161837628-2d17836d-85b4-4743-87f8-083f55cbdf16.png)

Current appearance:

![image](https://user-images.githubusercontent.com/296631/161837706-c844ade4-dbfd-4978-82ee-f79d59c53d05.png)

**Comment by urlsangel** [comment]
@harrislapiroff 

I started looking at this, but it's a bit tricky! I think to achieve this effect, the children of this block need to be `inline-block` or similar, but I couldn't quite get the desired look.

**Comment by harrislapiroff** [comment]
@shanejdonnelly this might be another good one for you, though based on @urlsangel's comments above it might actually be a bit tricky to pull off on the frontend only. If you can't work it out, let's coordinate with @SaptakS or @chigby to write a template filter that will get us the necessary `<span>`s to pull off this effect
