### ISSUE TITLE
Preview pages are giving 400 error—why?

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1379]

**Comment by chigby** [comment]
From [the logs](https://logs.freedom.press/app/discover#/doc/filebeat-*/filebeat-gke-2022.04.05?id=oFZm-38BYt8nOt3U3FwZ):

```
Invalid HTTP_HOST header: 'pressfreedomtracker.us'. You may need to add 'pressfreedomtracker.us' to ALLOWED_HOSTS.
```

**Comment by harrislapiroff** [comment]
Ah, okay, so it is domain specific. Thank god. Closing as we expect this to resolve when switched over.
