### ISSUE TITLE
Homepage incident cards should have more compact table as shown in Figma

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1387]
Homepage incident cards when seen in mobile and tab screens don't match the design with the one in figma.

**Comment by SaptakS** [comment]
I looked into this and it seems like that they had been working properly with the figma design. But at some point we added the classes for the database table incident cards, and unifying it caused it to behave like the database incident cards table. I think we need to separate those two.

**Comment by harrislapiroff** [comment]
@SaptakS Do you know if this is still an issue? If so, can you add a link to the Figma and maybe we can put @shanejdonnelly on it.

**Comment by SaptakS** [comment]
Yes this is still an issue. https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=4120%3A85035&t=CjA7WXK9wAxo1dgI-4 Both the featured incidents and the recent incidents have the card design different in figma. The key thing for this issue is separating the design for the database incident cards and the cards in the homepage, so that they can be separately implemented without affecting each other.

**Comment by dkaoster** [comment]
Wanted to ask before I got too far into this ticket, it looks like according to the figma file there are two different designs for latest incidents, which one of these should I be using?
![Screenshot 2023-03-23 at 11 28 14 AM](https://user-images.githubusercontent.com/3477162/227313016-97aec89e-2c03-408c-b310-f806a16bf53c.png)

**Comment by SaptakS** [comment]
@dkaoster in the screenshot that you have attachedm the left side design is when the "Show More +" item is collapsed, and the right side design is when the link is clicked and the content is expanded. So you need to implement both, and toggle betweent showing and hiding the design when "Show More +" item is clicked
