### ISSUE TITLE
Colors on homepage treemap shouldn't change

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1392]
I _believe_ the colors on the treemap are intended to be assigned by category, but they seem to shift as categories appear and disappear

Note how the categories change color in this video

https://user-images.githubusercontent.com/296631/162017351-0dc15f83-d011-4b52-a0b1-f6b09f5da952.mov

**Comment by SaptakS** [comment]
The video seems like colors are assigned by position rather than category.

**Comment by harrislapiroff** [comment]
Yeah, that's what I'm seeing too, but the code looked like it was trying to do something else? I haven't fully parsed out why it isn't

**Comment by urlsangel** [comment]
@SaptakS @harrislapiroff 

There are colors defined in `client/charts/js/lib/utilities.js` for categories - are these correct as far as you know?

```
export const categoriesColors = {
	'Arrest/Criminal Charge': '#669599',
	'Assault': '#E07A5F',
	'Border Stop': '#FBE0BC',
	'Chilling Statement': '#F4C280',
	'Denial of Access': '#7EBBC8',
	'Equipment Damage': '#B0829D',
	'Equipment Search or Seizure': '#63729A',
	'Leak Case': '#F9B29F',
	'Prior Restraint': '#98C9CD',
	'Subpoena/Legal Order': '#E2B6D0',
	'Other Incident': '#B2B8E5',
}
```

https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/client/charts/js/lib/utilities.js#L188

**Comment by harrislapiroff** [comment]
Yes, as far as I know, those should be the colors to use. (They only show up in one place on the site right now so across site consistency isn’t a concern at the moment.)
