### ISSUE TITLE
Tracker redesign feedback

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1414]
Capturing some requests from @stephaniesugars, we should triage and break out into separate tickets later:

> database filters:
> * the filtering by category -- one of the most important functions -- is kind of hidden down at the bottom
> * categories are not alphabetized
> * the arrangement of the date filters is counterintuitive for searching date ranges
> * it's not possible to search using multiple tags
> * it is no longer possible to search by when the incident was last updated
>
> metadata:
> * the arresting authority isn't capitalized throughout (e.g., 'Los angeles police department' instead of 'Los Angeles Police Department')
> * the style for identifying journos is confusing (e.g., it's odd to have 'John Smith for freelance'); the old style (NAME, OUTLET), not only allowed for this variation but also enabled clicking to filter by either name or outlet (currently clicking will only allow filtering by name)
>
> articles
> * updates aren't appearing in reverse chronological order -- while the updates are appearing above the main article, if there are more than one it's not showing the most recent first

**Comment by harrislapiroff** [comment]
I believe these have all now been resolved (tags search bullet point has an issue pending to make it easier)

**Comment by stephaniesugars** [comment]
As a note, it's still only possible to filter by just the name of a targeted journalist, rather than by either the name or the outlet they're affiliated with.
