### ISSUE TITLE
Not all incident detail pages offer clickpath/explanation for category

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/pressfreedomtracker.us#1433]
Example 1:
https://pressfreedomtracker.us/all-incidents/congressional-candidates-ad-touts-crowd-control-munition-use-against-press/

In this example, the meaning of the symbol is not explained in the incident summary - it's only at the bottom of the page under "Related incidents" that I see an explanation that this symbol stands for "Chilling Statement".

Example 2: 
https://pressfreedomtracker.us/all-incidents/reporter-arrested-phone-confiscated-while-covering-nc-homeless-camp-eviction/

In this case the icon is prominently explained, but I can't click to get to other pages in the same category except by way of the links under individual related incidents at the bottom.

I'm flagging these examples for discussion as I've not checked against the Figma design or prior issues if these are intentional tradeoff decisions. It seems to me that, at a minimum, we'll always want to make sure to explain the symbols.

**Comment by harrislapiroff** [comment]
@KAMcCudden has also pointed this out. One particular issue here is that the category names show up primarily as headers in the metadata table. But for categories that have no metadata fields specifically associated with them (e.g., Chilling Statement) there's nowhere to put a header. Compare these screenshots from the examples @eloquence shared:

![image](https://user-images.githubusercontent.com/296631/171492497-c53f08c6-15c4-4f1c-baea-9ad06eeb4c96.png)

![image](https://user-images.githubusercontent.com/296631/171492539-d4dc54d8-9ea8-467f-a207-33ff6f0f33c4.png)

Here's what I'd suggest to resolve these:

- [x] Experiment with displaying the table header for categories even if they have no metadata fields. Let's always display them at the _bottom_ if they have no metadata fields.
- [x] Turn the table headers into links to category pages
- [ ] Add a field for "Statement maker" (or some better name?) to the "Chilling Statement" so it has some metadata

**Comment by harrislapiroff** [comment]
Calling this ready for dev based on the checklist
