### ISSUE TITLE
Unparsed SASS variables in our CSS?

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1456]
I'm noticing what appears to be unprocessed SASS variables in our CSS. Someone should investigate what's going on there.

(Truthfully, I'd support relying more on CSS variables and less on SASS variables, where possible, so I'd accept getting rid of $font-base and $font-mono and replacing them with CSS vars instead.)

https://pressfreedomtracker.us/static/bundles/common-f4c7df23cc4888d4336e.css

![image](https://user-images.githubusercontent.com/296631/182200144-775d7d84-0ef0-40b8-bd1f-520d810cd758.png)

**Comment by SaptakS** [comment]
https://sass-lang.com/documentation/breaking-changes/css-vars This actually mentions why this is wrong. SASS has changed the syntax for using CSS variables and SASS variables in the same statement.
