### ISSUE TITLE
Python easy dependency updates

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1468]
Update the following packages:

- [x] bleach | 4.1.0 | 5.0.1 | 
- [x] django-anymail | 8.4 | 8.6 |  
- [x] django-modelcluster | 5.2 | 6.0 | 
- [x] django-storages | 1.12.3 | 1.13.1 |  
- [x] django-webpack-loader | 1.4.1 | 1.6.0 |  
- [x] drf-spectacular | 0.22.1 | 0.23.1 |  
- [x] drf-spectacular-sidecar | 2022.6.1 | 2022.8.1 |  
- [x] wagtail-factories | 2.0.1 | 3.1.0 |  
- [x] docutils | 0.18.1 | 0.19 |  
- [x] marshmallow | 3.15.0 | 3.17.0 |  
- [x] psycopg2 | 2.8.6 | 2.9.3 |  
- [x] pygments | 2.11.2 | 2.12.0 |  
- [x] wagtailmedia | 0.8.0 | 0.10.1 |  
- [x] wagtail-inventory | 1.4.1 | 1.5 |  
- [x] whitenoise | 5.3.0 | 6.2.0 |  
- [x] unittest-xml-reporting | 3.0.4 | 3.2.0

Remove:
- [ ] Jinja2
- [x] pyparsing

Also:
- [x]  Unpin structlog and update

**Comment by chigby** [comment]
It actually might not be possible to remove Jinja2. Witness this blast from the past:

https://github.com/freedomofpress/pressfreedomtracker.us/pull/556

Summary: Jinja2 is required by [typogrify](https://github.com/mintchaos/typogrify), a package we are still using in a couple places to convert plain text to HTML.

1. In the footer:
https://github.com/freedomofpress/pressfreedomtracker.us/blob/3fd24e0ada746b219ce74bb4213ed466fa664bae/common/templates/common/_footer_info.html#L7

2. In category page bodies
https://github.com/freedomofpress/pressfreedomtracker.us/blob/3fd24e0ada746b219ce74bb4213ed466fa664bae/common/templates/common/category_page.html#L18

**Comment by harrislapiroff** [comment]
WOW. I'm actually confused about the places we've chosen to use typogrify and why we saw it as necessary there and not in other places...

But probably best not to rabbit hole on this for the sake of dependency upgrades—leave it in.
