### ISSUE TITLE
Look into slow routes on Kibana

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1477]
Add Kibana link to this ticket

**Comment by chigby** [comment]
I tried to make a visualization to share, starting from the [Visualize Library](https://logs.freedom.press/app/visualize#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))) page, selecting Create Visualization then Lens. From there I could create a visualization but I was not able to save it, the Save button never becomes enabled for me.

**Comment by chigby** [comment]
Maeve fixed the permissions, so now I was able to save what I had before:

https://logs.freedom.press/app/dashboards#/view/f50fdff0-32ae-11ed-92cf-b76ec3d7f24d?_a=(viewMode:edit)&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))

**Comment by harrislapiroff** [comment]
Closing this—the dashboard @chigby made above is good and we should refer to it when working on performance optimziations in the future.
