### ISSUE TITLE
USPFT Metadata changes

### ISSUE THREAD

**Issue by stephaniesugars** [freedomofpress/pressfreedomtracker.us#1478]
In the vein of #1018, the Tracker team has reviewed the other categories as well and is requesting these updates ([detailed in full here with draft mock-ups](https://docs.google.com/document/d/1HPEAO641opu034WelRSkzaWC3lN4CIDz3z6m41R7z5o/edit#))

General asks:
- [x] Alphabetize the metadata categories (Legal case can/should be at bottom just before “related cases”)
- [x] On database filters page, display text for date filters is messed up: “took place between after” and “took place between before” (Switch to “took place after” and “took place before”)
- [x] Remove parenthetical “incl. legal case” from “leak prosecution” and “prior restraint”

Assault metadata
- [x] rename entry line from "physical assault" to just "assault"

Border Stop metadata
Remove: (will result in deleting this data from the database)
- [x] Stopped at border?
- [x] Did authorities ask for social media username?
- [x] Did authorities ask for social media password?
- [x] Were devices searched or seized?

~~Chilling Statement metadata (to be newly created)~~
~~- [ ] Add 'actor': (politician / public figure) [no recording of name]~~
~~- [ ] Add 'source of statement': (investigation / legal action / legislation / public statement / social media)~~
_Removed 2023-10-31 by @chigby for not being part of relevant Google doc_

Denial of Access metadata
- [x] Add “type of denial” (select all that apply): (changes in policy or practice / government events / other / press credential or media list) -- In progress https://github.com/freedomofpress/pressfreedomtracker.us/pull/1781
- [x] Rephrase existing language from 'Politicians or public officials involved' to 'Government agency or public official involved'

Equipment Damage metadata
- [x] Rename “Equipment Broken” to “Equipment Damaged”
- [x] Add actor (with the same general options that we use for assaults) above equipment entry (this should mirror equipment search/seizure) 
- [x] Rename button from “add equipment broken” to just “add equipment” with matching display text

Equipment Search or Seizure metadata
- [x] Merge “Equipment Seizure or Damage” into the existing “Equipment Searched or Seized" menu
- [x] Rename button from “add equipment search or seized” to just “add equipment” 
- [x] Remove 'Actor" as only actor viable for counting under the category is law enforcement

Prior Restraint metadata
~~- [ ] Add date entry fields for date ordered and date lifted~~
~~- If possible, we would love for this to essentially be used to field a "length of restraint" display metadata / potentially make "length of restraint" searchable. Date itself does not need to be added to filter.~~ Moved to https://github.com/freedomofpress/pressfreedomtracker.us/issues/1784
- [ ] Add "Mistakenly released materials?" checkbox

Subpoena/Legal Order metadata
_For "subpoena of journalism" entry field_
- [x] Rename as “Subpoena/legal order targeting journalist”
- [x] Akin to the arrest category changes: will have a "add legal order" button
- [x] From there, a “Select legal order type” [select one]: (motion to compel / subpoena / warrant / other)
- [x] Then, "Select information requested" : “communications or work product / testimony about confidential source / other testimony”
- [x] Status selection w/ date and button for adding additional statuses 

_For “Legal order for journalist’s records” entry field_
- [x] Rename as "Subpoena/legal order to third party"

**Comment by chigby** [comment]
[Latest document with the changes needed.](https://docs.google.com/document/d/1_zIuq8cL34tb2EDF3cgXnCU04ENdSRe41VagKNhmkAo/edit)

**Comment by eloquence** [comment]
(To do: Update checklist in issue consistent with GDoc)
