### ISSUE TITLE
Upgrade to wagtail 4.1

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1522]

**Comment by chigby** [comment]
Compatibility note: `wagtail-inventory` does not support wagtail 3+

https://github.com/cfpb/wagtail-inventory/issues/59

**Comment by chosak** [comment]
@chigby FYI, wagtail-inventory should now support through Wagtail 4.1. Please give [the latest version](https://pypi.org/project/wagtail-inventory/1.6/) a try and let us know if you run into any problems.

**Comment by harrislapiroff** [comment]
This ssems to have been completed here https://github.com/freedomofpress/pressfreedomtracker.us/pull/1540
