### ISSUE TITLE
Wagtail admin internal search not working

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1565]
Page search from within the Wagtail admin seems to work inconsistently. This was first noticed when the PFT editors were trying to search for pages in a page chooser panel, but it appears to be a broad issue with search, including when searching from the sidebar.

For example, "gag orders" search on pages successfully brings up the most recent blog post (this is an example of search working correctly):

https://pressfreedomtracker.us/admin/pages/search/?q=gag+orders
![image](https://user-images.githubusercontent.com/296631/210419862-5d242143-3206-48e6-9572-0273cf03f1f6.png)

But searching "protecting" does not bring up any blog posts, despite [at least one post](https://pressfreedomtracker.us/blog/protecting-reporters-privilege-even-after-death/) having it in the title:
![image](https://user-images.githubusercontent.com/296631/210419998-a5423a04-8308-434a-8dee-297002243a60.png)

(The issue is not case-sensitivity—I tested with both `P` and `p`)

**Comment by chigby** [comment]
Does running [`manage.py update_index`](https://docs.wagtail.org/en/stable/topics/search/indexing.html#the-update-index-command) help this?

**Comment by chigby** [comment]
I was able to essentially reproduce this on staging, where almost no pages seemed to be searchable in this way. I ran `manage.py update_index` on the staging server and now it seems much better. Probably worth a try to do on production.

@maeve-fpf Is that something you can arrange?

**Comment by maeve-fpf** [comment]
@chigby Done!

**Comment by chigby** [comment]
@maeve-fpf Thank you!

@harrislapiroff Can you check the search on the production server and see if it's any better?

**Comment by harrislapiroff** [comment]
@chigby This seems to have resolved it. I guess we'll see if the issue recurs if there's something awry in the signals that update search index!

@KAMcCudden, please verify that search is also working more consistently for you now and we'll close this ticket. If you notice search going wonky again, let us know!

**Comment by harrislapiroff** [comment]
Confirmed by Kirstin that this seems to be working now. Going to close this ticket and we'll keep an eye on search in the future to see if we need to schedule indexing.
