### ISSUE TITLE
Explore options for bar graphs with 0 incidents in a year

### ISSUE THREAD

**Issue by stephaniesugars** [freedomofpress/pressfreedomtracker.us#1567]
I noticed that on category pages, when the new bar graphs display the data, there is no bar for years where there are zero incidents. This is only really an issue for Border Stops at this point, and I've attached a screenshot. Kirstin and I don't have a solid idea yet of what a solution might look like, but would love to explore some options.

<img width="746" alt="Screenshot_20230104_025808" src="https://user-images.githubusercontent.com/50883722/210639128-449e844d-d694-45a8-95af-95cc80790067.png">

**Comment by harrislapiroff** [comment]
@dkaoster Maybe we should explicitly set date ranges for bar charts? Explicitly set to the range specified when there is one and 2017-present otherwise? What do you think?

**Comment by dkaoster** [comment]
@harrislapiroff I think it should be pretty easy to make sure 0 incidents are accounted for. There are a couple lines of code that should already do this but clearly it is not working - let me debug what is going on.
