### ISSUE TITLE
Analytics on filters sidebar and search bar

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1599]
I want to have better data on how users are navigating the site. Using [Matomo](https://matomo.org/) I can see requests like:

`/all-incidents/?categories=10&date_lower=2022-01-01&date_upper=2022-12-31`

which appear to show me that a user has used the Categories filter and data filters. But in actuality, they probably arrived at that URL by clicking the 2022 bar of the bar chart on the Assaults page:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/296631/226658724-7bf83b89-6977-44fa-8311-b52783f7e297.png">

I want to be able to better distinguish between that sort of interaction and a user actively using the sidebar filters:

![image](https://user-images.githubusercontent.com/296631/226660382-1fcd8846-c436-4336-afed-a23f01a8191b.png)

This ticket includes developing and implementing a system to do so. Please do some quick research to figure out the best approach. I suspect [Matomo event tracking](https://matomo.org/guide/reports/event-tracking/) will be useful here, but if you see a better approach go for it. (Don't overthink it, the priority is to spend minimal time on this so we can get to looking at the metrics.)

Add a comment to this PR describing your planned approach and get my approval before implementing.

**Comment by dkaoster** [comment]
Hi @harrislapiroff,

I spent some time looking at this today, and I agree with you that the event tracking API built into the Matomo library seems like the fastest and easiest way to accomplish getting the events you've described. I've also found even more documentation on javascript event tracking in matomo [here](https://developer.matomo.org/guides/tracking-javascript-guide).

Looking around in our codebase, it looks like the best way to implement this would be inside of [FiltersIntegration.jsx](https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/client/charts/js/components/FiltersIntegration.jsx) and all of the individual filter components we have underneath it.

Without being too familiar with Matomo and how it handles events within analytics dashboards, I'm thinking we can go ahead and fire events for any kind of interaction that a user does with the filter sidebar, even before they "apply filters". If you think that it would be better to only fire the event after users click the "apply filters" button, I can do it that way as well.

**Comment by harrislapiroff** [comment]
I think it makes sense to trigger these events on interaction. I'm also not super familiar with how Matomo handles events, but in the spirit of getting things done, let's try it this way and iterate as needed. A bit risky since I think Matomo events get recorded permanently, but in a worst case scenario we can always reach into the Matomo database and do a reset of the events table since we're not using those anywhere else yet :)

I welcome additional input from @freedomofpress/fpf-web-developers and @eloquence.

I just remembered that ages ago I was working on expanding analytics on freedom.press and in the process got a local matomo container up and running for testing purposes. You can look at my work here: https://github.com/freedomofpress/freedom.press/pull/731

If you think that sort of thing would be helpful while working on this feature, please tag in @chigby to help set up the docker container locally.
