### ISSUE TITLE
Evaluate `react-animated-dataset`

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1602]
The agency that did our redesign started the integration of charts using their own library [`react-animated-dataset`](https://github.com/accurat/react-animated-dataset). I'm interested in getting @dkaoster evaluation of this library and whether we should continue to use it or consider something else as we go down the path of integrating more data visualizations into the site. Some considerations:

* Our plan is to create a few standard chart types that editors will be able to select a dataset for and embed through some sort of gui interface. You can see the list of potential chart types in [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=1893-9469&t=GRLKbZEhnX4kQdJa-0)
* We like React, so it's nice to have something that's React-native and minimizes the amount of raw D3 we have to write
* react-animated-dataset isn't super consistently maintained by Accurat, so if we need to patch it in any way it's possible we'll have to do that patching ourselves
* On the other hand, in my brief skim of the code, it's not a particularly complicated library, so that may not be so hard to do.

Spent up to 2 hours (if less, so much the better) evaluating it and writing up a recommendation.

**Comment by dkaoster** [comment]
Looking through this, I have a couple of thoughts:

1. `react-animated-dataset` is a pretty simple wrapper around D3 data joins and transition management. 
2. It does a pretty clean job of abstracting away most of the D3 implementation details into a flexible react component. However, there are still some D3 abstractions that leak through making the props options slightly confusing if you aren't familiar with D3.
3. I think it would be possible to still use `react-animated-dataset` within any standard chart types that we will create.

I think my general conclusion is that `react-animated-dataset` wouldn't be too hard for us to copy / make our own version of if we're worried about future maintainability, and it does do some helpful things such as abstracting D3's data join model into the react world. Data joins are one of the most complex parts of D3 that doesn't usually play nice with modern "reactive" javascript frameworks, so it's nice to have all that logic inside of a component.

**Comment by harrislapiroff** [comment]
Thanks for your evaluation! Based on this, let's move forward with keeping `react-animated-datatset`.
