### ISSUE TITLE
Embed in blog posts a vertical bar chart showing counts of incidents over time

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1608]
Add a vertical bar chart stream block.

- [x] Allow content editors to select which data to use for the bar chart (OK to limit to category, tag, and date range filters for now)
- [x] Render a vertical bar chart in the blog post (the x-axis should be date, the y-axis should be incident count)
- [x] **Stretch goal:** A screenreader should produce reasonable audio of the chart. Ideally this would be a readout of each bar label and value. If it's not practical to complete this with the current version of `react-animated-dataset` let's open a separate ticket to track it in the future.

[Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=2031-5227&t=i2IiB2EU1RUwVS5u-4)

**Comment by dkaoster** [comment]
I'm looking at the `/styleguide/` endpoint that this application also spins up for development purposes, and I'm wondering if it would also make sense to have a copy of these charts on that page too? That way I can maybe start developing the chart on the styleguide page while @chigby adds the stream block?

edit: I just noticed there's a [`chartpage.html`](https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/charts/templates/charts/chartpage.html) file presumably for this purpose, although it's just rendering a blank page for me, is this still in use?

@chigby I've started a branch `vertical-bar-chart` for this work, if you'd like to do it all in one branch.
