### ISSUE TITLE
Blog index page design for newsletter and special blog templates

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1617]
We need to add a special teaser format for the special blog templates in the blog index page as shown in the design by accurat below.

![image](https://user-images.githubusercontent.com/296631/230919952-2487f517-9839-4b88-9b03-f58a940cd541.png)

Also, we need to add a tab UI to swap between the different kind of blog posts (articles, newsletter, special section)

![image](https://user-images.githubusercontent.com/296631/230920131-b536119e-5854-4b25-be07-eb3f18fe6551.png)

[Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3689-54926&t=q92LFBtIBwAa4rUz-4)

_Originally posted by @harrislapiroff in https://github.com/freedomofpress/pressfreedomtracker.us/issues/1595#issuecomment-1501879718_

Deliverables:
- [ ] Update index page layout to include the special blog teaser
- [ ] Add a tab to swap between different blog types

**Comment by SaptakS** [comment]
@harrislapiroff one question related to the UI. Is it fine if there is a page load on switching between the blog types in the tab? Or do you want to handle the switch to work with javascript? I will definitely anyways do progressive enhancement in case we want the javascript on the fly kind of interaction.

**Comment by harrislapiroff** [comment]
Yeah, I think this is a progressive enhancement situation! Start with the page reload and then make it snappier with javascript.

**Comment by harrislapiroff** [comment]
Assigning this to @chigby so @SaptakS can focus back on FPF. Let me know if you have any questions about it @chigby!

**Comment by chigby** [comment]
Do people have thoughts about if/how this new filter button row should interact with the old filter capabilities of the blog index page? Examples: [organizations](https://staging.pressfreedomtracker.us/blog/?organization=44), [authors](https://staging.pressfreedomtracker.us/blog/?author=1514). These did not really have any UI associated with them but it might change the possibilities for varieties that the page type filter can interact with.

My initial thoughts are that the simplest thing to do is always show the buttons. But then we might end up in a scenario where filtering by type on top of an organization filter might produce no results. Which is possibly fine, but maybe each button should only be shown (or clickable?) if it would yield some posts.

**Comment by chigby** [comment]
Another question: what ordering are we expecting here for the special template? From the design image it seems like we the special template should be full-width, but the row above it has four items. Do we want to enforce that using something like [`grid-auto-flow: dense`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow#values) even if it means the posts will not appear in the grid in strict chronological order?

**Comment by SaptakS** [comment]
I remember me and @harrislapiroff having this discussion initially while implementing the redesign (probably during a web sync), and I think at that time, we had decided 2 different possible solutions (if my memory is not betraying me):
- `grid-auto-flow: dense` : We definitely at least want this it seems to maintain the design shown in the index page. Actually in this solution, the chronological order is only messed up visually, but in HTML it still apppears chronologically (i.e. for keyboard users, screen reader users it appears in chronological order). But because of this, the focus ordering of the elements is broken.
- Treat chronology of special blogs separate from rest: I remember we had little discussion about thinking of the chronology of special blogs separate from the other blog items, i.e. the special blogs by themselves should appear in chronology even though they are out of order with the rest. I think this is what happens visually anyways in the first solution. I feel like we had some discussion of creating the HTML such that it's 8 non-special blog, followed by 1 special blog, or something like that. That way the focus ordering is also maintained.

But since we decided not to implement the newsleterr and special blog templates at that time, we didn't have any further discussion. Though I think the solutions might still be feasible, I haven't fully thought after that if there are any pros or cons to them, or if there is a separate solution that works better than both of them. But I remember that the general consensus was that it's fine to treat the chronology of special blogs separate from the others.

**Comment by chigby** [comment]
Another question about this: for the teaser image that's display in the grid of cards, are there any size parameters I should be considering? From the Figma designs:

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/561931/6d7266f7-3ef7-4f63-a894-1a870ab19a9a)

It looks like the special cards have a kind of minimum height, but I'm not sure how that's being determined or if that's documented anywhere. Any thoughts?

**Comment by chigby** [comment]
From meeting: use wagtail to crop images to the same size and maybe use srcsets and/or the picture element for responsivity.

**Comment by harrislapiroff** [comment]
You captured it as I said it @chigby! That sounds right to me. In general, I'm interested in letting wagtail crop images to the size that we're going to use them rather than cropping them client size with `background-image` or what have you, since Wagtail has information about the primary focus of an image. Using `srcset` and/or `picture` seems like a good way to let Wagtail provide multiple different crops.

Possibly we should add some help text to the UI to advise editors to be attentive to setting a focus area and check on the different crops? But it's a little tricky to know where to add it since this only really applies if they've marked a blog post post as a special section...
