### ISSUE TITLE
[API] Updates to methodology and methodology items for API

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1632]
Continuing work from #1337. Currently a category in the API looks like this:

```json
    {
        "id": 10,
        "title": "Assault",
        "methodology": "<p data-block-key=\"pdugx\">Journalists who face physical violence, either as the result of a targeted attack by a public or private individual or in the course of their work. If a journalist is hit by rubber bullets or bean bag rounds, it will be counted in this category.</p><p data-block-key=\"4d87i\">Damage to equipment is counted in a separate &quot;<a id=\"345\" linktype=\"page\">Equipment Damage</a>&quot; category, but may be also listed in this Assault category if the damage occurs with an attack.</p><p data-block-key=\"gllp8\">Journalists affected by tear gas, pepper spray or other mass riot control agents will be counted if the individual suffers serious injury or appears to have been specifically targeted. Incidents that fall outside these parameters and in which multiple journalists were affected by riot control agents may be counted in the “<a id=\"63\" linktype=\"page\">Other</a>” category.</p>",
        "plural_name": "Physical Attacks",
        "slug": "assault",
        "url": "https://pressfreedomtracker.us/assault/"
    },
```

Two changes needed:

- [ ] `methodology` field is actually Wagtail's internal rich text format (note: `<a id="63" linktype="page">`). If we want to provide this through the API as HTML rich text, we need to run it through Wagtail's rich text filter.
- [ ] We should also provide a `methodology_items` array field which is a related object `CategoryPage`s have

**Comment by dkaoster** [comment]
my bad on this one, I wasn't quite sure looking at the last ticket what exactly that was - I should have asked. I'll look through the docs and see how to do this.

**Comment by harrislapiroff** [comment]
Oh that's actually even a _separate_ thing that I also didn't catch.

Editors have the option, for each category, of listing the fields associated with that category and explanations of each field. It doesn't look like editors are using this right now, but it might be nice to add that information to the API if they do use it sometime in the future. I'd say that's more of a "nice to have" at this point, though.

**Comment by harrislapiroff** [comment]
Updated ticket description to include methodology items and provide more clarity on the tasks involved
