### ISSUE TITLE
Further Data Visualizations

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1636]
Now that we have a working [vertical bar chart](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1614), let's implement some other visualization stream blocks. Here's what we should have along with some completion criteria for each. 

Editors being able to select which incidents to include in the dataset is completion criteria for each and should be accomplished in the same way as with the vertical bar chart. I imagine you'll want to create a reusable class for some of these fields.

Please complete each chart in a separate PR, queuing if needed. Please also include screenshots of the completed work in each PR description so review of the visuals is easy :)

- [ ] Treemap ([Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=2462-12651&t=YQgBwECdekhCewgM-4))

  - [ ] Editors should be able to select which incidents to include in the dataset

  - [ ] Design: Should rotate to vertical when viewport is narrow (responsive)

  - [ ] Design: Let's try to achieve an accessibility tree that looks something like this (if this is too complicated to achieve with react-animated-dataset, leave it incomplete for now and we'll discuss later):

        list "Categories"
           listitem "Arrests and Criminal Charges: 10 incidents"
           listitem "Subpoenas and Legal Orders: 7 incidents"
           listitem "Equipment Search and Seizures: 3 incidents"
           ...

      One useful thing here might be to recall that the categories API has a `plural_name` field for each category.

  - [ ] It might be nice to keep the code flexible enough that in the future we can give editors the option to choose what field to segment by (say, `arresting_authority` instead of `categories`) but don't spend too much work on this until we know it's a feature editors will use. I can imagine this being deceptively complex since different fields have different formats and tallying methods.

- [ ] Bubble Map ([Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=2803-18928&t=YQgBwECdekhCewgM-4))

  - [ ] Editors should be able to select which incidents to include in the dataset

  - [ ] Editors should be able to select whether to aggregate by `city, state` or just `state`

  - [ ] Design: Bubble tooltips as documented in the Figma

  - [ ] Design: Let's try to achieve an accessibility tree that looks something like this (if this is too complicated to achieve with react-animated-dataset, leave it incomplete for now and we'll discuss later):

        list "U.S. Map"
           listitem "Portland OR: 207 incidents"
           listitem "Seattle WA: 17 incidents"
           ...

  - [ ] **Stretch Goal** Location dropdown as documented in the Figma

Figma exports below to save your browser memory:

![Treemap](https://user-images.githubusercontent.com/296631/234351046-01106b9e-84fe-4284-8825-110006ae3d68.png)

![Bubble Map](https://user-images.githubusercontent.com/296631/234351056-90f6e6dc-45d7-4119-93ac-c8e6a4ca1f4b.png)

**Comment by dkaoster** [comment]
I'm working on Bubble Map and looking at this one in particular:

>  Editors should be able to select whether to aggregate by city, state or just state

For states, it looks like `groupByState` [function here](https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/client/charts/js/lib/utilities.js#LL221C1-L221C1) will add the longitude and latitude values to each aggregated value, because it pulls it from a json file that lives in the repo which maintains the longitude and latitude values for each state.

However, it looks like we do not have the same for cities, which means that it is currently not possible to plot the cities on a map. I'm wondering if we want to try to also add a json with a list of coordinates for cities like we are doing for states? I am afraid that that file could be quite large, and may not be worth the effort / increased download costs. What do we think about this?

**Comment by harrislapiroff** [comment]
@dkaoster Fun fact: we do the geocoding of cities server side, so every incident has `latitude` and `longitude` fields in the API that should correspond 1:1 with the city/state field combo. So you just need a different javascript path for deducing coords depending on which grouping you're using. (Possibly we should consider embedding both in the API or having a separate endpoint for geocoding?)

**Comment by dkaoster** [comment]
@harrislapiroff I noticed that the incidents are getting geocoded on api calls to the production website, but looks like in my local instance all of the longitude and latitude values are returning as empty strings. Is there a way I can enable it locally for development or does this functionality only work on the live site?

**Comment by harrislapiroff** [comment]
Hm, this may be a limitation of our development data, since we haven’t actually used the lat/long feature in the past (just provided it in the api). @chigby if you could take a look at this in the AM and offer recommendations, that would be great.

**Comment by chigby** [comment]
Posting my comment on slack here for visibility: https://freedomofpress.slack.com/archives/CA04P1PGR/p1683213501614979?thread_ts=1683162622.266259&cid=CA04P1PGR
