### ISSUE TITLE
Allow charts to be the "primary image" for blog posts

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1658]
(I've rethought this since I first drafted this, so apologies if you saw the substantially different previous version)

Accurat's [Figma files](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?type=design&node-id=3689-55821&t=PEyeZsQ2CW6xdy34-4) allow blog posts to have charts as their primary image:

Blog page:
![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/b6cbcd80-c726-4bf3-bbe0-6f04426c69c3)

Blog index page:
![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/57722231-d676-45e8-92c7-dd9706186b94)

Here's how I'd like this to be implemented:

- [ ] Let's make the "lead image" field into a streamblock that can accept a single image block or any of our chart types
- [ ] Image or chart block gets rendered above the intro text on blog posts, as pictured in the mockup—full site width
- [ ] If the lead image is an image, we render thumbnails on the blog index page same as now
- [ ] If the lead image is a chart we render a simplified version of the chart, as pictured in the mockup above
   - [ ] **Stretch goal:** Simplified chart should be interactive and show a tooltip on hover, much like the full chart. We should probably include the chart title in the tooltip since the context of the page won't be around it
   - [ ] **Stretch goal:** We should render the chart server side to be the open-graph image (I'm guessing this won't actually be feasible without introducing a node rendering process into our server side setup, but adding this item in case I'm mistaken)
   - [ ] Vertical bar chart should be rendered vertically even though only horizontal bar chart thumbnails are shown in the mockup
   - [ ] There's no mockup for a simplified bubble map, so feel free to invent one, or render it as is

**Comment by dkaoster** [comment]
@harrislapiroff I'm wondering how far I should go with the open graph image that you're mentioning in the description. I think it would be nice to have this image be present for social media and also for users that may use the site without javascript, but this will require some backend service that can essentially render these charts into a static image that is then linked to on the site. I actually think this would be a really nice feature and would like to try to figure it out.

I think that means that I can write some of that code in python? Maybe even integrated with wagtail? I'm honestly not quite sure how the pieces will fit together or if it really is ultimately worth the effort, but open to hearing your thoughts!

**Comment by harrislapiroff** [comment]
@dkaoster I’m intrigued! Let’s talk about this in our 1:1 later today.
