### ISSUE TITLE
Check if scheduled publishing is running

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1715]
@KAMcCudden reports that a few hours passed after a blog post's scheduled go live time it still hadn't been published. Let's check if we're running the appropriate management commands.

**Comment by harrislapiroff** [comment]
@maeve-fpf This is a question for you. Are we running `./manage.py publish_scheduled` on a cron job? This would be good to run hourly or even every 30m on PFT (and on all of our sites actually).

**Comment by maeve-fpf** [comment]
We have `publish_scheduled_pages` in daily tasks (on all sites), but that's only once a day. Should we set up a job for hourly tasks as tell?

**Comment by harrislapiroff** [comment]
@maeve-fpf Oh, that might account for the issue if it wasn't timed for shortly after Kirstin's scheduled publish time! Can we run the task hourly or every 30m if that's not too burdensome? It should be very quick when there's nothing to publish (and quick even when there is).

Just to catch you up, I do think @mig5 made some changes yesterday, maybe updating to the new command name (`publish_scheduled` vs `publish_scheduled_pages` which is deprecated).

**Comment by mig5** [comment]
@harrislapiroff do you want the scheduled publish task to run more frequently on *all* sites or just PFT?

**Comment by harrislapiroff** [comment]
@mig5 All sites, please!
