### ISSUE TITLE
Consider implementing Conditional View Processing

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1719]
Django provides a number of tools for helping to add [Conditional View Processing](https://docs.djangoproject.com/en/3.2/topics/conditional-view-processing/) via the `ETag` and `Last-Modified` headers that help clients decide what information/resources are cached and don't need to be retrieved again from the server. These are additions we might want to make to our API endpoints (or others, maybe?) to ease the computational burden on our server.

### Further reading

* [Conditional HTTP GET: The fastest requests need no response body ](https://ieftimov.com/posts/conditional-http-get-fastest-requests-need-no-response-body/)
* [Django Project Optimization](https://dizballanze.com/django-project-optimization-part-3/)
* [`django-rest-framework-condition`](https://github.com/jozo/django-rest-framework-condition)

**Comment by harrislapiroff** [comment]
Timebox 1hr and report back

**Comment by chigby** [comment]
In my opinion, the fundamental problem that ETags (and related) are solving is very similar to what our front end caching with Cloudflare is solving. The procedure for computing, say, an etag for a request is very similar to our procedure for deciding what pages need their cache invalidated in Cloudflare. This process is already known to be somewhat flaky. The data that's displayed on any single PFT page (or API requests) is potentially pulled from many different database tables/rows that all have different last-updated timestamps. I don't think it's worth building a parallel system for doing this kind of computation when we already have one for Cloudflare.

Second, Django Rest Framework's support for Etag headers is not built-in, and there _is_ a plugin that allows the use of Django's `condition` decorator, but it's a plugin and it's doesn't look all that up to date on things (it's the third link in the issue description). Not feeling that optimistic about building a system that relies on that.

**Comment by harrislapiroff** [comment]
Hearing no strong opinions from anyone that we definitely _should_ do this I am going to close this ticket. If anyone (@chigby or anyone else) disagrees, feel free to reopen.
