### ISSUE TITLE
Smart Search Phase 1

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1767]
Okay, let's actually try to get phase one of the smart search in! Here's the spec

<img width="1440" alt="1  Basic search" src="https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/414af2a9-c48d-49e3-a962-16052abd2269">

- [ ] When in focus the search bar pops up a dropdown showing the same list of tags that are used for the homepage data viz
- [ ] A user can type text into the search bar, causing the dropdown to disappear
- [ ] A user can click a tag from the dropdown causing the tag to appear in the search bar with a # next to it and the dropdown to disappear
  - [ ] This isn't in the above spec but let's also render a × next to the tag that will clear the field when clicked, since there's no other way to clear it right now (the "next steps" in the spec seem to apply to a later iteration)
- [ ] A user can also select a tag using the arrow keys and enter button
- [ ] Submitting the search form behaves differently depending on its contents:
  - [ ] If a tag is contained within, it goes to the database page with a tag filter applied
  - [ ] If free text is contained within, it goes to the database page with a text search

In developing this be attentive to making the code flexible, clean and ready to adapt to new features. You can look at the figma to see what the next phases look like: https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?type=design&node-id=4495-110643&mode=design&t=7XimrARBwTXy6QZb-4

**Comment by harrislapiroff** [comment]
I believe for accessibility this component should follow the [Combobox Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/). @SaptakS please chime in if you have anything to add about it.

**Comment by dkaoster** [comment]
@harrislapiroff when you say 

> When in focus the search bar pops up a dropdown showing the same list of tags that are used for the homepage data viz

Do you mean tags or categories? The homepage data viz uses categories which is why I'm a little confused.

**Comment by harrislapiroff** [comment]
Ah, sorry for the confusion. I mean these tags:

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/3c826b72-e020-4093-8daf-df4aa3cb6918)
