### ISSUE TITLE
Fix "New York City" geoname entry to match our incident database entries

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1797]
In our incidents database, there are a number of incidents with the `city` field set to `New York`. There is no corresponding geoname for this city. The one in the `geonames.geonames` table is `New York City`. We want to update the geoname to match our use of the city name.

In my opinion, this is best done by running this query:

```sql
UPDATE geonames_geoname SET name = 'New York' WHERE name = 'New York City';
```

In the Django shell, this is:

```python
from geonames.models import GeoName
GeoName.objects.filter(name="New York City").update(name="New York")
```

To fix the incidents currently in production:

1. Run the above query/shell commands.
2. Either:
    - Run the `./manage.py populate_geodata` command. This will update all incidents to have their lat/long data reflect the updated geonames DB, including the ones with the city "New York"
    - Refresh the incident lat/long data one-by-one loading the ones you want to fix in the wagtail editor and issuing a "Publish" command.

Additionally, we will want to apply this change everywhere we can, so we should update the fixtures to use the correct name.

The easiest way to do this is to:

1. Ensure that the fixtures have been loaded in the local dev environment (`docker compose exec django ./manage.py loaddata --app geonames cities500-us-only.json.xz`)
2. Update the DB using the query or shell commands from above.
3. Regenerate the fixtures: `docker compose exec django ./manage.py dumpdata geonames -o geonames/fixtures/cities500-us-only.json.xz`

**Comment by harrislapiroff** [comment]
@freedomofpress/fpf-infra @enpaul Can we arrange to run the query steps above (including either the django shell or sql query) first on staging and then on prod? To be clear, that is (or could be):

```sh
./manage.py django shell
>>> from geonames.models import GeoName
>>> GeoName.objects.filter(name="New York City").update(name="New York")
```

and then also 

```sh
./manage.py populate_geodata
```

**Comment by mig5** [comment]
@harrislapiroff I've just gone ahead and run those commands on the 'staging' PFT instance.

(One small difference: I needed to run `./manage.py shell`, not `./manage.py django shell`, as the latter throws the error `Unknown command 'django'`).

Here is the output, I thought it best if you double-check it before we try on production:

```
gcorn@pft-wagtail-567698557b-p5p2m:/django$ ./manage.py shell
/usr/local/lib/python3.12/site-packages/wagtail/contrib/modeladmin/apps.py:15: RemovedInWagtail60Warning: wagtail.contrib.modeladmin is deprecated. Use wagtail.snippets or the separate wagtail-modeladmin package instead.
  warn(
Python 3.12.2 (main, Feb 13 2024, 09:28:52) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from geonames.models import GeoName
>>> GeoName.objects.filter(name="New York City").update(name="New York")
1
>>> 
now exiting InteractiveConsole...
gcorn@pft-wagtail-567698557b-p5p2m:/django$ ./manage.py populate_geodata
/usr/local/lib/python3.12/site-packages/wagtail/contrib/modeladmin/apps.py:15: RemovedInWagtail60Warning: wagtail.contrib.modeladmin is deprecated. Use wagtail.snippets or the separate wagtail-modeladmin package instead.
  warn(
gcorn@pft-wagtail-567698557b-p5p2m:/django$ 
```

Does that look right to you (the return `1` after having run the update command, and no output for the populate_geodata, other than the unrelated warnings)?

**Comment by harrislapiroff** [comment]
@mig5 Whoops, yep, I malformed that command. Thanks for catching and fixing. That looks right and the data looks correct and consistent on staging now. Please make a backup of the prod database just in case and then run on prod. Thank you so much 🙏

**Comment by enpaul** [comment]
@harrislapiroff I'll start the prod conversion (starting with the backup) now!

Backup command:
```
kubectl -n pressfreedomtracker create job pft-backup-sql-issue1797 --from=cronjob/pft-backup-sql
```

**Comment by enpaul** [comment]
All set @harrislapiroff 

```
gcorn@pft-wagtail-5996644bf8-k9vzm:/django$ ./manage.py shell
/usr/local/lib/python3.12/site-packages/wagtail/contrib/modeladmin/apps.py:15: RemovedInWagtail60Warning: wagtail.contrib.modeladmin is deprecated. Use wagtail.snippets or the separate wagtail-modeladmin package instead.
  warn(
Python 3.12.2 (main, Feb 13 2024, 09:28:52) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from geonames.models import GeoName
>>> GeoName.objects.filter(name="New York City").update(name="New York")
1
>>> 
now exiting InteractiveConsole...
gcorn@pft-wagtail-5996644bf8-k9vzm:/django$ ./manage.py populate_geodata
/usr/local/lib/python3.12/site-packages/wagtail/contrib/modeladmin/apps.py:15: RemovedInWagtail60Warning: wagtail.contrib.modeladmin is deprecated. Use wagtail.snippets or the separate wagtail-modeladmin package instead.
  warn(
gcorn@pft-wagtail-5996644bf8-k9vzm:/django$ 
exit
```

**Comment by harrislapiroff** [comment]
@KAMcCudden @stephaniesugars New York City should now be corrected to New York. Please verify that things are working as you expect and we can close this ticket :)

**Comment by harrislapiroff** [comment]
Have confirmed this is working as expected. I don't feel strongly about updating the fixtures, but @chigby, if you do, we can leave this open. Otherwise we should close.
