### ISSUE TITLE
Smart Search Phase Two

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1804]
Here's the spec from Accurat for Smart Search Phase Two—feel free to ask me any questions about the intention of any parts of the design or any gaps we need to fill in that aren't accounted for in this spec:

<img width="1440" alt="2  One filter option" src="https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/b384ba84-c598-42e4-9b29-2cc4b33c5292">

**Comment by chigby** [comment]
Is the "type again in the search box to see more suggestions and add more options" part of the spec something we want to implement as part of this issue?

**Comment by dkaoster** [comment]
It's something that I could potentially add, although should I just make my own decisions on how the design would look with that? There don't seem to be designs for more than one tag, category, or search term in the figma

**Comment by chigby** [comment]
Feels like a question for @harrislapiroff

**Comment by harrislapiroff** [comment]
Yeah, it doesn't seem clear to me what the UX should be for that feature so let's just skip it for now
