### ISSUE TITLE
Fix alignment in incident data table

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1813]
In some pages like https://pressfreedomtracker.us/all-incidents/florida-journalists-barred-from-covering-gov-desantis-signing-of-controversial-new-election-law/, the target row is overflowing and not aligning correctly with the rest of the rows. 
![Screenshot 2023-12-21 at 12-51-16 Florida journalists barred from covering Gov  DeSantis signing of controversial new election law](https://github.com/freedomofpress/pressfreedomtracker.us/assets/9530293/32856520-bb9b-4cad-ae8a-4168f8d3d2ab)

I think a solution could be using grid in CSS instead of flex? But haven't really looked closely.

**Comment by chigby** [comment]
Adding another page where this is the case (hat tip: @sophieongithub) https://pressfreedomtracker.us/all-incidents/reporters-removed-kansas-senate-floor-threatened-loss-press-passes/

**Comment by sophieongithub** [comment]
And here! https://pressfreedomtracker.us/all-incidents/reporters-excluded-press-briefing/
