### ISSUE TITLE
Manually enable SVG support

### ISSUE THREAD

**Issue by stephaniesugars** [freedomofpress/pressfreedomtracker.us#1838]
Manually enable SVG support so the Tracker team can use that file type for high-quality graphics in the future.

***

**Harris's notes**

Looks like we need to:

- [ ] add the SVG file extension to `WAGTAILIMAGES_EXTENSIONS` in settings 
- [ ] add the `preserve-svg` option to `{% image %}` template tags

see: https://docs.wagtail.org/en/stable/topics/images.html#svg-images

(going to copy this issue to other repos as well because we might as well)

**Comment by harrislapiroff** [comment]
Note, the SVG in question is the map in this post: https://pressfreedomtracker.us/blog/the-public-is-paying-the-price-for-local-government-secrecy/

This also speaks to a need to provide more custom data visualization options, including the ability to upload custom data and chart along custom axes.
