### ISSUE TITLE
Slider not working on mobile bar charts

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1840]
![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/9e17396b-5550-46f0-8c76-9a3d63c3450c)

Expected behavior: scrubbing across the slider changes which bar is selected and shows details for it

Actual behavior: scrubbing across the slider doesn't move the slider

This makes it look like a weird design element and like we're weirdly highlighting one bar for no reason!

**Comment by zrobert7** [comment]
Note: you can click on the various year buttons, just not drag. I will try to improve this interaction!
