### ISSUE TITLE
Weird period after month

### ISSUE THREAD

**Issue by sophieongithub** [freedomofpress/pressfreedomtracker.us#1858]
In the metadata for arrest charges, I noticed a period after "May" - I'm wondering if the system is automatically adding a period after the first three letters of a month name.
![Screenshot 2024-05-06 at 11 45 38 AM](https://github.com/freedomofpress/pressfreedomtracker.us/assets/87768517/1d3bd09e-2129-4983-a74b-ec163a08d339)

**Comment by sophieongithub** [comment]
hey all, just flagging another instance of this (in this case, a period after "May"): https://pressfreedomtracker.us/all-incidents/wikileaks-founder-julian-assange-arrested-and-charged-conspiracy/

**Comment by chigby** [comment]
@sophieongithub Your theory is right, it is adding the period after the abbreviation by default. [Here's](https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/incident/models/inlines.py#L43) the code. What do you think the solution here is, remove the period in all cases? 

Actually, looking into this slightly more, it looks like the [AP style](https://writingexplained.org/ap-style/ap-style-months) does not match the built-in date formatter we're currently using. Maybe that's another way to go?

**Comment by sophieongithub** [comment]
exactly - we want to have it match AP style if possible. Is that possible?

**Comment by chigby** [comment]
It's definitely possible
