### ISSUE TITLE
PFT Home Page Data Viz Vertical Bar Chart Display

### ISSUE THREAD

**Issue by KAMcCudden** [freedomofpress/pressfreedomtracker.us#1864]
Issue: When you filter the database from our homepage by a tag, the resulting vertical bar chart (far right DV) shows 12 months that sometimes / often belong across many different years on the x-axis 

Two screenshots attached as examples:
1. Filtering for the tag "Israel-Gaza war" / "all time" = bar chart showing 12 months that belong across two different years, with Jan.-May belong to 2024 and Oct.-Dec. belong to 2023 (it loops, essentially, but no way to tell user that info);

2. Filtering for the tag "Black Lives Matter" / "all time" = a bar chart showing data from 2017-present, but May is distorted (due to 2020)

Solutions include, but are not limited to — when a user selects "all-time," the bar chart reflects incidents by year rather than month (similar to the "last 6 months" view); replace Jan with a year number if there are multiple years displayed, etc

![Screenshot 2024-05-21 at 15 51 18](https://github.com/freedomofpress/pressfreedomtracker.us/assets/46460749/146f7138-71a4-4bdc-990a-76f159279d76)
![Screenshot 2024-05-16 at 2 43 08 PM](https://github.com/freedomofpress/pressfreedomtracker.us/assets/46460749/d1b8e07d-0de2-475a-8116-c0720da5dcd0)

Acceptance criteria:

- [ ] When "All time" is selected, histogram is broken up by year
- [ ] When "last six months" is selected, histogram range only includes last six months, in order
- [ ] Otherwise, display full year as 12 months in order
- [ ] Clicking a bar should take you to an appropriately filtered all incidents page without an error in displaying the filters
- [ ] Chart should still look reasonable under a scenario: "All incidents" is selected, but a tag is selected that only has incidents during one year

If this turns out to look much larger than a medium issue, please raise to the web team before proceeding.

There are multiple possible ways of implementing this, most likely. The view parameters could be hard coded differently or the bar chart could intelligently select how to break down the data based on what data it is passed. This is left up to the implementer.

**Comment by eloquence** [comment]
It looks like the data is at least accurate? Adding up the numbers from the different years it does seem to be correct. But I agree it's confusing.

Switching to by-year seems to make the most sense here, IMO. There also _is_ a bug here, when you click on the individual months, it takes you to a page like this, which is partially broken due to JavaScript errors:
https://pressfreedomtracker.us/all-incidents/?date_lower=null-11-01&date_upper=null-11-30&tags=Israel-Gaza+war

**Comment by KAMcCudden** [comment]
correct -- the month-over-month data is _accurate_ even though misleading

**Comment by eloquence** [comment]
@KAMcCudden Just discussed a bit with Harris, we can commit to delivering a fix in the course of the next two week sprint, which begins 11/25 (minus Thanksgiving).

**Comment by KAMcCudden** [comment]
Sounds great thank you On Nov 19, 2024, at 15:41, Erik Moeller ***@***.***> wrote:﻿
@KAMcCudden Just discussed a bit with Harris, we can commit to delivering a fix in the course of the next two week sprint, which begins 11/25 (minus Thanksgiving).
