### ISSUE TITLE
Create Stylebook for Tracker fonts/palettes

### ISSUE THREAD

**Issue by KAMcCudden** [freedomofpress/pressfreedomtracker.us#736]
Create a shareable document of Tracker fonts/color palettes.
Can be used for marketing materials, creation of new assets.
Creates a succession plan for Tracker fonts/colors so that not dependent on singular developer

**Comment by harrislapiroff** [comment]
I think @conorsch is correct that this was accomplished with files I've shared with @KAMcCudden
