### ISSUE TITLE
Explore how Tracker can house ongoing databases in better visual forms

### ISSUE THREAD

**Issue by KAMcCudden** [freedomofpress/pressfreedomtracker.us#743]
Say wha? Exploratory committee and timeline for adding long-term projects to Tracker, and giving front-page presence to them. Example: From most recent Steering Committee meeting a consensus that Tracker could hold and uphold projects such as this [Trump Tweet database](https://pressfreedomtracker.us/blog/fake-news-enemy-people-anatomy-trumps-tweets/) and other long-term projects (being commissioned through fellowships this year). 
Ideas for temporary and permanent solutions. 
E.g. Temporary: Bug on front page "We're counting Trump's tweets about the media" that links to locked database and story
E.g. Long-term: Special Project area on front page with special internal section

**Comment by harrislapiroff** [comment]
This was a feature @KAMcCudden requested early on, but I think it has now been covered by the ability to feature blog posts and topic pages on the home page #830 #929 and our ability to integrate more rich content onto the homepage #949
