### ISSUE TITLE
Verify caching behavior on pressfreedomtracker.us

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#745]
@KAMcCudden just posted an incident, which is currently live on the site, but is not showing up on the homepage. I'm not sure what's going on here.

* Kirstin says no server error was raised
* I also noticed that that the All Incidents page was successfully purged—it's showing the incident—so it doesn't seem to be an issue of consistently missing the cloudflare API server
* The correct signal appears to be hooked up in the code https://github.com/freedomofpress/tracker/blob/master/home/signals.py#L21
* The cache did seem to clear _eventually_—like 30 minutes later—with no intervention

I have no idea what this is but we should figure it out. We could just implement the nuclear caching option as @conorsch has been advocating and see if that fixes it.

I wonder if there's also some way to log all outgoing calls to cloudflare's server so we can identify if the correct endpoints are in fact getting hit.

![image](https://user-images.githubusercontent.com/296631/52358518-232f8d00-2a06-11e9-9e3f-a399b6144fcf.png)

**Comment by eloquence** [comment]
Since PFT is already on k8s, now would IMO be a good time to check if the caching behavior there is what we want, which could also inform the freedom.press migration. Added to "needs scoping" for now, but I think this is ready for additional follow-up.

**Comment by eloquence** [comment]
We've not observed caching issues in production since the k8s migration, so we're closing this for now until we observe any specific issues that need follow-up.
