### ISSUE TITLE
Individualize "status" fields for targets

### ISSUE THREAD

**Issue by ssempervirens** [freedomofpress/pressfreedomtracker.us#778]
Currently, although multiple journalists/institutions can be listed as "targets" in one incident, fields like "status of charges" can only be modified for one incident, rather than for each journalist. This became an issue recently, I believe in the Sacramento arrest case, when two journalists had charges dropped but one did not, and we were all very confused.

**Comment by eloquence** [comment]
@harrislapiroff Could you re-check the priority of this request? Not adding to "Ready for dev" for now.

**Comment by harrislapiroff** [comment]
The tracker team now just separates different journalists into different incidents. It's more straightforward and obviates this issue.
