### ISSUE TITLE
Building Images into Layout: Not resizing, no caption/credit info

### ISSUE THREAD

**Issue by KAMcCudden** [freedomofpress/pressfreedomtracker.us#953]
When added an image via the layout builder, it didn't automatically re-size to fit within the screen.
There also isn't the ability to add caption or credit info.

When added the image within the rich text layout, was given the ability to choose full-width, left or right alignment (but still no caption or credit info).

One screenshot shows the image added via rich text and, directly below it, (a portion of) the image when added via Image button from the layout builder (it's so big can only see a portion of it)

I've worked-around the image/caption for right now by adding the image within the  rich text, then putting the caption right below, and a line below the caption. this does not give it a credit, though, ad the caption words are not properly formatted.

![Screen Shot 2020-08-24 at 10 19 56 AM](https://user-images.githubusercontent.com/46460749/91059278-84727d80-e5f7-11ea-8986-8e7d93d7cad4.png)
![Screen Shot 2020-08-24 at 10 20 49 AM](https://user-images.githubusercontent.com/46460749/91059282-850b1400-e5f7-11ea-92cb-ae5ab83951b5.png)
![Screen Shot 2020-08-24 at 10 21 08 AM](https://user-images.githubusercontent.com/46460749/91059283-850b1400-e5f7-11ea-9c24-48240fd4d3e3.png)
![Screen Shot 2020-08-24 at 10 44 47 AM](https://user-images.githubusercontent.com/46460749/91059284-850b1400-e5f7-11ea-8da5-84f585fed4eb.png)

**Comment by SaptakS** [comment]
I think this should be fixed (or mostly addressed) by https://github.com/freedomofpress/pressfreedomtracker.us/pull/989

**Comment by harrislapiroff** [comment]
We have these features now! We should go back and clean up uses of the old block at the same time as resolving #808
