### ISSUE TITLE
Enable live preview functionality on k8s

### ISSUE THREAD

**Issue by maeve-fpf** [freedomofpress/pressfreedomtracker.us#975]
Currently we cannot enable live preview on a deployment with more than one backend server. This includes our GKE environment, since there are multiple pods running Django at any given time. After some testing and looking at browser network requests, I believe this is because:

- Live preview looks like it works by:
  - When an edit is made on the client, the updated content is POSTed to `/admin/pages/:id/edit/live_preview/`
  - On the backend, the page body is rendered to a temporary file (in `TMPDIR`, which is either a directory in `/var` somewhere or a tmpfs)
  - On the client, a jquery timer runs once a second and GETs  `/admin/pages/:id/edit/live_preview/`, which serves the pre-rendered content, to avoid hammering the render path
- On a deployment with a single Django backend, this request always serves the file that was written
- On a deployment with multiple Django backends, requests are load balanced (in our case, simply round-robinned), and only the backend that handled the POST has the updated file
  - This results in the "cycling" between the last edits behavior that we observe

This isn't specific to Kubernetes, it would also apply to a deployment consisting of a couple hardware servers and a hardware LB.

Generally this is solved by using something like memcache/Redis as the backing store instead of files. We can do this.

However, we may also be able to configure live preview to not use the tempfiles-and-poll pattern, but instead only make one request per edit and render the content statelessly. On further inspection, the POST returns only `{"is_valid": "true"}`; I don't really see a good reason for this to not return the rendered content (edits are already debounced on the client, so rendering only happens once per second-where-an-edit-it-made, not every keystroke).

I'm not familiar with the live preview implementation, so there may be some reason it has to poll. @harrislapiroff, any thoughts?

**Comment by eloquence** [comment]
This is ready for development, but let's wait until post-inauguration and check in with Kirstin to see if we're ready to make changes.
