### ISSUE TITLE
Better image management

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#985]
Kirstin has been using the "Title" field on Wagtail images to add searchable information about the images themselves. This isn't ideal since the title field also serves extra duty as the accessible `alt` attribute for images. This ticket covers a few issues:

- [ ] Add a note to the title tag similar to what we have on freedom.press articulating that the field is used for accessibility
- [x] Talk to Kirstin about what info she needs to track about images
- [x] Figure out to what extent that info can be managed using the already built in collections functionality
- [ ] Add a `slug` field that Kirstin and co can use to stash the filename that they use to track the image through the editorial process. This does not need to be a `SlugField`—we can allow spaces and symbols, so just a `CharField` will do.

**Comment by eloquence** [comment]
Next step is for @harrislapiroff to review recent improvements in Wagtail w/ Kirstin to determine if any development effort from us is required here.

**Comment by harrislapiroff** [comment]
The major thing @KAMcCudden is running into now is not knowing if she's used an image before when she finds it on Reuters.

Not sure the best way to solve this—could be a process thing, maybe search for duplicate images when uploading, maybe building a direct integration to reuters images so the db can track usage?

**Comment by harrislapiroff** [comment]
Okay, after chatting with @KAMcCudden this is better specced out in the first comment and I'm marking it ready for dev
