### ISSUE TITLE
Make PFT settings consistent with other apps

### ISSUE THREAD

**Issue by maeve-fpf** [freedomofpress/pressfreedomtracker.us#986]
Following up on https://github.com/freedomofpress/tracker/pull/984: There are a few quirks in each app's settings that we'd like to make a little more unified. Things we can do on PFT:

- Instead of `DJANGO_NO_DB`, check for the presence of `DJANGO_DB_HOST` like other apps
- Create a setting for `DJANGO_ONION_HOSTNAME` (in case we want to use it in a template, i.e. footer link)
- Stub out a CSP variable, to add entries later
- Instead of `DJANGO_LOG_CONSOLE` and `DJANGO_LOG_PATH`, just log to console if a log path is not set. Don't require `DJANGO_LOG_JSON`, default it appropriately.
- Treat env vars that should be "booleans" consistently (I like `.get` without a default, for type soundness)

**Comment by SaptakS** [comment]
@maeve-fpf @harrislapiroff this issue can be closed?

**Comment by eloquence** [comment]
Closed per web sync today.
